name: "✨ Feature request"
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please describe the feature clearly and what problem it solves.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: "Right now it’s hard to…"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      placeholder: "Add a feature that…"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Workarounds or other approaches you considered..."
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Mockups, screenshots, examples of receipts, related printers, etc.
    validations:
      required: false
